SELECT s.INST_ID ,s.SID,s.serial# serial, s.USERNAME ,s.COMMAND ,s.CLIENT_INFO ,s.MACHINE ,s.MODULE ,s.ACTION,s.PROCESS ,
W.EVENT, W.SECONDS_IN_WAIT, SQL.SQL_TEXT
FROM GV$SESSION_WAIT W,
GV$SESSION S,
GV$PROCESS P,
GV$SQLTEXT SQL
WHERE W.SID = S.SID
AND S.PADDR = P.ADDR
AND SQL.ADDRESS = S.SQL_ADDRESS
AND SQL.HASH_VALUE = S.SQL_HASH_VALUE
AND W.WAIT_CLASS != 'Idle'
AND W.INST_ID = S.INST_ID
AND W.INST_ID = P.INST_ID
AND W.INST_ID = SQL.INST_ID
ORDER BY W.SECONDS_IN_WAIT, W.SID, SQL.PIECE ;