  SELECT SESSION_KEY,
  INPUT_TYPE, STATUS,
  TO_CHAR(START_TIME,'DD/MM/YYYY HH24:MI') START_TIME,
  TO_CHAR(END_TIME,'DD/MM/YYYY HH24:MI') END_TIME,
  trunc(ELAPSED_SECONDS/3600,2) HRS,
   decode(STATUS,'FAILED','TRUE','FALSE') ATTENTION
   FROM V$RMAN_BACKUP_JOB_DETAILS
  WHERE  INPUT_TYPE='DB FULL'
  UNION all
  SELECT SESSION_KEY,
  INPUT_TYPE, STATUS,
  TO_CHAR(START_TIME,'DD/MM/YYYY HH24:MI') START_TIME,
  TO_CHAR(END_TIME,'DD/MM/YYYY HH24:MI') END_TIME,
  trunc(ELAPSED_SECONDS/3600,2) HRS,
   decode(STATUS,'FAILED','TRUE','FALSE') ATTENTION
   FROM V$RMAN_BACKUP_JOB_DETAILS
  WHERE INPUT_TYPE='DB INCR'
  UNION all
  SELECT SESSION_KEY,
  INPUT_TYPE, STATUS,
  TO_CHAR(START_TIME,'DD/MM/YYYY HH24:MI') START_TIME,
  TO_CHAR(END_TIME,'DD/MM/YYYY HH24:MI') END_TIME,
  trunc(ELAPSED_SECONDS/3600,2) HRS,
   decode(STATUS,'FAILED','TRUE','FALSE') ATTENTION
   FROM V$RMAN_BACKUP_JOB_DETAILS
  WHERE INPUT_TYPE not in ('ARCHIVE','DB FULL')
  ORDER BY SESSION_KEY ;