--Tanel Poder
-- geeky shorcuts for producing date ranges for various ASH scripts
define          1s="sysdate-1/24/60/60 sysdate"
define          5s="sysdate-1/24/60/12 sysdate"
define         10s="sysdate-1/24/60/6 sysdate"
define         30s="sysdate-1/24/60/2 sysdate"
define           m="sysdate-1/24/60 sysdate"
define         min="sysdate-1/24/60 sysdate"
define        1min="sysdate-1/24/60 sysdate"
define      minute="sysdate-1/24/60 sysdate"
define        5min="sysdate-1/24/12 sysdate"
define          5m="sysdate-1/24/12 sysdate"
define       10min="sysdate-1/24/6 sysdate"
define         10m="sysdate-1/24/6 sysdate"
define       15min="sysdate-1/24/4 sysdate"
define         15m="sysdate-1/24/4 sysdate"
define       30min="sysdate-1/24/2 sysdate"
define         30m="sysdate-1/24/2 sysdate"
define           h="sysdate-1/24 sysdate"
define          1h="sysdate-1/24 sysdate"
define        hour="sysdate-1/24 sysdate"
define       1hour="sysdate-1/24 sysdate"
define      2hours="sysdate-2/24 sysdate"
define      4hours="sysdate-4/24 sysdate"
define      6hours="sysdate-6/24 sysdate"
define      8hours="sysdate-8/24 sysdate"
define     12hours="sysdate-12/24 sysdate"
define     24hours="sysdate-1 sysdate"
define          1h="sysdate-1/24 sysdate"
define          2h="sysdate-2/24 sysdate"
define          4h="sysdate-4/24 sysdate"
define          6h="sysdate-6/24 sysdate"
define          8h="sysdate-8/24 sysdate"
define         12h="sysdate-12/24 sysdate"
define         24h="sysdate-1 sysdate"
define           d="sysdate-1 sysdate"
define         day="sysdate-1 sysdate"
define   yesterday="sysdate-2 sysdate-1"
define       2days="sysdate-2 sysdate"
define       3days="sysdate-3 sysdate"
define       4days="sysdate-4 sysdate"
define       5days="sysdate-5 sysdate"
define          2d="sysdate-2 sysdate"
define          3d="sysdate-3 sysdate"
define          4d="sysdate-4 sysdate"
define          5d="sysdate-5 sysdate"
define       today="TRUNC(sysdate) sysdate"
define           w="sysdate-7 sysdate"
define        week="sysdate-7 sysdate"
define       4week="sysdate-28 sysdate"
define      4weeks="sysdate-28 sysdate"
define          4w="sysdate-28 sysdate"
         
define            S="sql_id"
define           S1="session_state,event"
define           S2="session_state,wait_class,event"
define           S3="session_state,wait_class,sql_id"
define           S4="session_state,wait_class"
define           PM="program,module,action,client_id,machine"
define            F="session_type='FOREGROUND'"
define            B="session_type='BACKGROUND'"
define            C="""session_state='ON CPU'"""
define          CPU="""session_state='ON CPU'"""
define           IO="""wait_class='User I/O'"""
