apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://rockdb_prometheus:9090
  isDefault: true
  access: proxy
  editable: true

- name: VictoriaMetrics
  uid: victoriametrics
  type: prometheus
  url: http://rockdb_victoriametrics:8428
  access: proxy
  editable: true

- name: rockdb_influxdb
  uid: cfca5jww9ysxsa
  type: influxdb
  access: proxy
  url: http://rockdb_victoriametrics:8428
  basicAuth: false
  jsonData:
    version: InfluxQL
    organization: rockdb
    defaultBucket: timemachine
    httpMode: POST
    tlsSkipVerify: true
  editable: true